"""
NEXUS — Layer 3 / Brain 1: SIGMA Rule Engine
Loads SIGMA-style rules and matches them against log entries.
Pure Python — no x86 deps, ARM64-safe.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ── Rule Model ────────────────────────────────────────────────────────────────

@dataclass
class SigmaRule:
    rule_id: str
    title: str
    description: str
    severity: str               # low | medium | high | critical
    technique: str              # MITRE ATT&CK ID
    conditions: list[dict]      # list of {field, operator, value}
    auto_generated: bool = False
    hit_count: int = 0

    def matches(self, log: dict) -> bool:
        """Return True if ALL conditions match the log entry."""
        for cond in self.conditions:
            field_val = log.get(cond["field"])
            op = cond["operator"]
            target = cond["value"]

            if field_val is None:
                return False

            if op == "eq" and str(field_val) != str(target):
                return False
            if op == "in" and str(field_val) not in [str(v) for v in target]:
                return False
            if op == "contains" and str(target).lower() not in str(field_val).lower():
                return False
            if op == "gte" and not (float(field_val) >= float(target)):
                return False
            if op == "lte" and not (float(field_val) <= float(target)):
                return False
            if op == "regex" and not re.search(target, str(field_val)):
                return False

        return True


# ── Alert ─────────────────────────────────────────────────────────────────────

@dataclass
class SigmaAlert:
    rule_id: str
    title: str
    severity: str
    technique: str
    log: dict
    confidence: float = 1.0


# ── Engine ────────────────────────────────────────────────────────────────────

class SigmaEngine:
    """
    Loads, stores and evaluates SIGMA rules against log streams.
    Rules can be added manually or auto-generated by the Evolution Engine.
    """

    def __init__(self):
        self.rules: list[SigmaRule] = []
        self._load_baseline_rules()

    def _load_baseline_rules(self):
        """Ten hand-crafted baseline SIGMA rules — Week 1 starting point."""
        baseline = [
            SigmaRule(
                rule_id="SIG-001",
                title="Successful Logon to Domain Controller",
                description="Any successful logon to a DC that is not from a known admin host.",
                severity="high",
                technique="T1078",
                conditions=[
                    {"field": "event_id", "operator": "eq", "value": 4624},
                    {"field": "host",     "operator": "contains", "value": "DC"},
                    {"field": "attack_technique", "operator": "eq", "value": "T1078"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-002",
                title="Process Creation — PowerShell",
                description="PowerShell process creation detected.",
                severity="medium",
                technique="T1059",
                conditions=[
                    {"field": "event_id", "operator": "eq", "value": 4688},
                    {"field": "attack_technique", "operator": "eq", "value": "T1059"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-003",
                title="LSASS Access — Credential Dumping",
                description="Access to LSASS process, possible credential dumping.",
                severity="critical",
                technique="T1003",
                conditions=[
                    {"field": "event_id",         "operator": "eq", "value": 4662},
                    {"field": "attack_technique",  "operator": "eq", "value": "T1003"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-004",
                title="Mass File Modification — Ransomware Indicator",
                description="High volume of file modification events — possible ransomware.",
                severity="critical",
                technique="T1486",
                conditions=[
                    {"field": "event_id",         "operator": "eq", "value": 4663},
                    {"field": "attack_technique",  "operator": "eq", "value": "T1486"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-005",
                title="Outbound C2 Beacon",
                description="Windows Filtering Platform permitted unusual outbound connection.",
                severity="high",
                technique="T1071",
                conditions=[
                    {"field": "event_id", "operator": "eq", "value": 5156},
                    {"field": "attack_technique", "operator": "eq", "value": "T1071"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-006",
                title="Remote Interactive Logon — Lateral Movement",
                description="Remote logon (RDP/WinRM) from unexpected source.",
                severity="high",
                technique="T1021",
                conditions=[
                    {"field": "event_id",         "operator": "eq", "value": 4624},
                    {"field": "attack_technique",  "operator": "eq", "value": "T1021"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-007",
                title="Process Injection Detected",
                description="Sysmon event 10 — possible process injection.",
                severity="critical",
                technique="T1055",
                conditions=[
                    {"field": "event_id", "operator": "eq", "value": 10},
                    {"field": "attack_technique", "operator": "eq", "value": "T1055"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-008",
                title="File and Directory Enumeration",
                description="Unusual file access pattern — possible reconnaissance.",
                severity="low",
                technique="T1083",
                conditions=[
                    {"field": "event_id",         "operator": "eq", "value": 4663},
                    {"field": "attack_technique",  "operator": "eq", "value": "T1083"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-009",
                title="Valid Account Abuse",
                description="A simulated valid-account attack was observed.",
                severity="high",
                technique="T1078",
                conditions=[
                    {"field": "event_id",  "operator": "eq",       "value": 4624},
                    {"field": "attack_technique", "operator": "eq", "value": "T1078"},
                ],
            ),
            SigmaRule(
                rule_id="SIG-010",
                title="Explicit Credential Use",
                description="Account attempted logon using explicit credentials (runas-style).",
                severity="medium",
                technique="T1078",
                conditions=[
                    {"field": "event_id", "operator": "eq", "value": 4648},
                    {"field": "attack_technique", "operator": "eq", "value": "T1078"},
                ],
            ),
        ]
        self.rules.extend(baseline)

    # ── Detection ─────────────────────────────────────────────────────────────

    def analyze_log(self, log: dict) -> list[SigmaAlert]:
        """Run all rules against a single log entry. Return matching alerts."""
        alerts = []
        for rule in self.rules:
            if rule.matches(log):
                rule.hit_count += 1
                alerts.append(SigmaAlert(
                    rule_id=rule.rule_id,
                    title=rule.title,
                    severity=rule.severity,
                    technique=rule.technique,
                    log=log,
                ))
        return alerts

    def analyze_stream(self, logs: list[dict]) -> list[SigmaAlert]:
        """Run all rules against a list of log entries."""
        alerts = []
        for log in logs:
            alerts.extend(self.analyze_log(log))
        return alerts

    # ── Rule Management ───────────────────────────────────────────────────────

    def add_rule(self, rule: SigmaRule):
        """Add a new rule (e.g. auto-generated by evolution engine)."""
        # Avoid duplicate IDs
        existing_ids = {r.rule_id for r in self.rules}
        if rule.rule_id not in existing_ids:
            self.rules.append(rule)

    def get_missed_techniques(self, logs: list[dict],
                              detection_results: list[dict] | None = None) -> list[str]:
        """
        Return techniques where the ensemble produced false negatives.

        If detection_results (serialised DetectionResult dicts) are provided,
        use them to find logs where ensemble said 'benign' but label was 'malicious'.
        This is more accurate than technique-level rule coverage because a rule
        can exist and still be bypassed by a crafted log (e.g. NOVA evasion).

        Falls back to technique-vs-rule-coverage comparison if no results provided.
        """
        if detection_results:
            # Find techniques that slipped through the full ensemble
            missed: set[str] = set()
            for r in detection_results:
                if (r.get("true_label") == "malicious"
                        and r.get("ensemble_verdict") == "benign"
                        and r.get("technique")):
                    missed.add(r["technique"])
            return list(missed)

        # Legacy fallback: pure SIGMA coverage gap
        attacked = {log["attack_technique"] for log in logs
                    if log.get("label") == "malicious" and log.get("attack_technique")}
        detected = {a.technique for a in self.analyze_stream(logs)}
        return list(attacked - detected)

    def stats(self) -> dict:
        return {
            "total_rules": len(self.rules),
            "auto_generated": sum(1 for r in self.rules if r.auto_generated),
            "rule_hits": {r.rule_id: r.hit_count for r in self.rules if r.hit_count > 0},
        }

    def save_rules(self, path: str = "data/sigma_rules.json"):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            json.dump([r.__dict__ for r in self.rules], f, indent=2)

    def load_rules(self, path: str = "data/sigma_rules.json"):
        if not Path(path).exists():
            return
        with open(path) as f:
            data = json.load(f)
        for item in data:
            rule = SigmaRule(**item)
            self.add_rule(rule)
