import codecs

with codecs.open('research/paper_generator.py', 'r', 'utf-8') as f:
    text = f.read()

# Remove the graphs from the paper generator
old_sections = """            "\\n" + self.project_info(),
            "\\n" + self.tactical_details(campaign_record),
            "\\n" + self.results(campaign_record),
            "\\n## 6. Threat Evolution Visualization\\n",
            "![ELO Chart](data/research/elo_chart.png)\\n",
            "![MITRE Chart](data/research/mitre_chart.png)\\n",
            "\\n" + self.appendix_personas(campaign_record),
            "\\n" + self.appendix_sigma_log(campaign_record)"""

new_sections = """            "\\n" + self.project_info(),
            "\\n" + self.tactical_details(campaign_record),
            "\\n" + self.results(campaign_record),
            "\\n" + self.appendix_personas(campaign_record).replace("Appendix A:", "6. Attacker Persona Profiles"),
            "\\n" + self.appendix_sigma_log(campaign_record).replace("Appendix B:", "7.")"""

text = text.replace(old_sections, new_sections)

# Let's cleanly format the SIGMA rule log so it's not a weird split list
old_sigma = """    def appendix_sigma_log(self, campaign_record) -> str:
        h = campaign_record.sigma_rule_history
        lines = ["## Appendix B: SIGMA Rule Evolution Log\\n"]
        if not h:
            lines.append("*(No SIGMA rules generated)*\\n")
            return "\\n".join(lines)

        lines.append(f"- Baseline rules at campaign start: {h[0]}")
        lines.append(f"- Rules at campaign end: {h[-1]}")
        lines.append(f"- Auto-generated by Evolution Engine: {h[-1] - h[0]}\\n")
        lines.append("Rule count per battle:")
        for i, val in enumerate(h):
            lines.append(f"Battle {i+1}: {val} rules")
        return "\\n".join(lines)"""

new_sigma = """    def appendix_sigma_log(self, campaign_record) -> str:
        h = campaign_record.sigma_rule_history
        lines = ["## 7. SIGMA Rule Evolution Log\\n"]
        if not h:
            lines.append("*(No SIGMA rules generated)*\\n")
            return "\\n".join(lines)

        lines.append(f"The Evolution Engine actively synthesizes new SIGMA detection rules in response to zero-day adversarial behaviors. The campaign started with {h[0]} baseline rules and concluded with {h[-1]} active rules, representing the autonomous generation of {h[-1] - h[0]} new behavioral heuristics across the {len(h)} live operations.\\n")
        return "\\n".join(lines)"""

text = text.replace(old_sigma, new_sigma)

# Also rename Appendix A in the method definition just in case
text = text.replace('lines = ["## Appendix A: Attacker Persona Profiles\\n"]', 'lines = ["## 6. Attacker Persona Profiles\\n"]')

with codecs.open('research/paper_generator.py', 'w', 'utf-8') as f:
    f.write(text)
